# constantes utilizadas para as demandas do Wrike !
ID_FOLDER_TESTE = 'IEADYSXZI42H3JBZ'
ID_FOLDER_ESCUTA = 'IEADYSXZI42H3JCP'
ID_TAREFA_TESTE = ''

ID_CUSTOM_VALOR_UNITARIO = 'IEADYSXZJUABQ27R'
ID_CUSTOM_EH_FATURAVEL='IEADYSXZJUABQ3JE'
ID_CUSTOM_CUSTO_INTERNO='IEADYSXZJUABRTMH'
ID_CUSTOM_QTDE='IEADYSXZJUABRTMT'
ID_CUSTOM_TOTAL_REAL = 'IEADYSXZJUABVECO'