ID_CUSTOM_VALOR_UNITARIO = 'IEADYSXZJUABQ27R'
ID_CUSTOM_QTD = 'IEADYSXZJUABRTMT'
ID_CUSTOM_CUSTO_INTERNO = 'IEADYSXZJUABRTMH'
ID_CUSTOM_VALOR_HONORARIO = 'IEADYSXZJUABRTM6'
ID_CUSTOM_RECEITA = 'IEADYSXZJUABVSGX'
ID_CUSTOM_VALOR_REAL = 'IEADYSXZJUABVECO'
ID_TEM_HONORARIO = 'IEADYSXZJUABRTN6'
ID_CUSTOM_BOX_TIPO_CUSTO = 'IEADYSXZJUACYMQE'
ID_CUSTOM_VALORTERCEIRO = 'IEADYSXZJUACYMNA'
ID_CUSTOM_VALOR_ENCARGO = 'IEADYSXZJUACYMNC'
ID_CUSTOM_PORCENTAGEM_ENCARGO = 'IEADYSXZJUACYMNB'
ID_CUSTOM_CNPJ_FORNECEDOR = 'IEADYSXZJUACZAJL'
ID_CUSTOM_NOME_FORNECEDOR = 'IEADYSXZJUACZAJN'


#Custom fields METAS
ID_CUSTOM_META_TAREFA_MAE = 'IEADYSXZJUACZATC'